name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18.x'
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Code Quality and Linting
  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: |
          npx prettier --check . --ignore-path .prettierignore || {
            echo "Code formatting issues found. Running prettier --write to fix..."
            npx prettier --write .
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git diff --staged --quiet || git commit -m "Auto-fix code formatting with Prettier"
          }

      - name: TypeScript type checking
        run: npm run type-check

  # Unit and Integration Tests
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --coverage --watchAll=false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  # Security Scanning
  security:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level high

      - name: Run dependency check
        run: npx audit-ci --config audit-ci.json

      # Tạm thời comment OWASP ZAP vì cần app chạy trước
      # - name: OWASP ZAP Security Scan
      #   uses: zaproxy/action-full-scan@v0.7.0
      #   with:
      #     target: 'http://localhost:3000'
      #   continue-on-error: true

  # Build Application
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local from secrets
        run: |
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}" >> .env.local

      - name: Verify environment setup
        run: |
          echo "Environment variables set:"
          grep -c "NEXT_PUBLIC" .env.local || echo "No env vars found"

      - name: Build application
        run: |
          echo "Starting Next.js build..."
          npm run build
          echo "✅ Build completed successfully"

      - name: Verify build output exists
        run: |
          if [ ! -d ".next" ]; then
            echo "❌ Build failed - .next directory not found!"
            echo "Available files and directories:"
            ls -la
            exit 1
          fi
          echo "✅ .next directory exists"
          echo "Build output size:"
          du -sh .next
          echo "Key files in .next:"
          find .next -name "*.js" -o -name "*.json" | head -10

      # Upload cả thư mục .next và node_modules cần thiết
      - name: Upload Next.js build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: |
            .next/
            package.json
            package-lock.json
            public/
          if-no-files-found: error
          retention-days: 1

  # End-to-End Tests
  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        browser: [chrome] # Chỉ test chrome trước, tránh quá nhiều job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .

      - name: Verify downloaded artifacts
        run: |
          echo "Checking downloaded .next directory:"
          if [ -d ".next" ]; then
            echo "✅ .next directory found"
            ls -la .next/
          else
            echo "❌ .next directory not found after download"
            echo "Available files:"
            ls -la
            exit 1
          fi
          
      - name: Install Cypress dependencies
        run: npx cypress install

      - name: Start application in background
        run: |
          npm start &
          echo $! > .next_pid
        env:
          PORT: 3000

      - name: Wait for application to start
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }} --config video=true,screenshotOnRunFailure=true
        continue-on-error: true

      - name: Stop application
        run: |
          if [ -f .next_pid ]; then
            kill $(cat .next_pid) || echo "Process already stopped"
          fi

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
          if-no-files-found: ignore

  # Performance Testing
  performance:
    name: Performance Testing
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .

      - name: Start application
        run: |
          npm start &
          echo $! > .next_pid
        env:
          PORT: 3000

      - name: Wait for application to start
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun --upload.target=temporary-public-storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        continue-on-error: true

      - name: Stop application
        run: |
          if [ -f .next_pid ]; then
            kill $(cat .next_pid) || echo "Process already stopped"
          fi

      # Comment load testing tạm thời
      # - name: Run load testing
      #   run: |
      #     npm install -g artillery
      #     artillery run performance/load-test.yml

  # Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [lint, test, security, build, e2e]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.enterprise-app.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .

      - name: Deploy to Vercel Staging
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          scope: ${{ secrets.TEAM_ID }}
          alias-domains: staging.enterprise-app.com

      - name: Deploy Firebase Functions (Staging)
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --project staging --token ${{ secrets.FIREBASE_TOKEN }}
        continue-on-error: true

      - name: Update Firebase Security Rules (Staging)
        run: |
          firebase deploy --only firestore:rules,storage --project staging --token ${{ secrets.FIREBASE_TOKEN }}
        continue-on-error: true

      - name: Run smoke tests on staging
        run: |
          npx cypress run --config baseUrl=https://staging.enterprise-app.com --spec "cypress/e2e/smoke/**/*"
        continue-on-error: true

  # Deploy to Production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [deploy-staging, performance]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://enterprise-app.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .

      - name: Deploy to Vercel Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
          scope: ${{ secrets.TEAM_ID }}

      - name: Deploy Firebase Functions (Production)
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --project production --token ${{ secrets.FIREBASE_TOKEN }}
        continue-on-error: true

      - name: Update Firebase Security Rules (Production)
        run: |
          firebase deploy --only firestore:rules,storage --project production --token ${{ secrets.FIREBASE_TOKEN }}
        continue-on-error: true

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            ## Changes in this Release
            - Auto-generated release from main branch
            - Commit: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Notify deployment success
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#deployments'
          message: |
            ✅ Production deployment successful!
            Version: v${{ github.run_number }}
            URL: https://enterprise-app.com
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: env.SLACK_WEBHOOK_URL != ''

  # Cleanup
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: always()
    steps:
      - name: Clean up artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: nextjs-build
          failOnError: false

      - name: Clean up old deployments
        run: |
          echo "Cleaning up completed successfully"